services:
    netgen_layouts.sylius.bitbag.backend.bitbag_page:
        class: Netgen\Layouts\Sylius\BitBag\ContentBrowser\Backend\PageBackend
        arguments:
            - "@netgen_layouts.sylius.bitbag.page_repository"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: bitbag_page }

    netgen_layouts.sylius.bitbag.backend.bitbag_section:
        class: Netgen\Layouts\Sylius\BitBag\ContentBrowser\Backend\SectionBackend
        arguments:
            - "@netgen_layouts.sylius.bitbag.section_repository"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: bitbag_section }

    netgen_layouts.sylius.bitbag.backend.bitbag_block:
        class: Netgen\Layouts\Sylius\BitBag\ContentBrowser\Backend\BlockBackend
        arguments:
            - "@netgen_layouts.sylius.bitbag.block_repository"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: bitbag_block }

    netgen_layouts.sylius.bitbag.backend.bitbag_media:
        class: Netgen\Layouts\Sylius\BitBag\ContentBrowser\Backend\MediaBackend
        arguments:
            - "@netgen_layouts.sylius.bitbag.media_repository"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: bitbag_media }

    netgen_layouts.sylius.bitbag.backend.frequently_asked_question:
        class: Netgen\Layouts\Sylius\BitBag\ContentBrowser\Backend\FrequentlyAskedQuestionBackend
        arguments:
            - "@netgen_layouts.sylius.bitbag.frequently_asked_question_repository"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: bitbag_frequently_asked_question }

    netgen_layouts.sylius.bitbag.backend.component:
        class: Netgen\Layouts\Sylius\BitBag\ContentBrowser\Backend\ComponentBackend
        arguments:
            - "@netgen_layouts.sylius.bitbag.component_repository"
            - "@sylius.context.locale"
            - "@netgen_content_browser.config.bitbag_component"
        tags:
            - { name: netgen_content_browser.backend, item_type: bitbag_component }
