services:
    netgen_layouts.sylius.bitbag.backend.bitbag_page:
        class: Netgen\Layouts\Sylius\BitBag\ContentBrowser\Backend\PageBackend
        arguments:
            - "@netgen_layouts.sylius.bitbag.page_repository"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: bitbag_page }
