services:
    netgen_layouts.sylius.bitbag.item.value_converter.page:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueConverter\PageValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.bitbag.item.value_loader.page:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueLoader\PageValueLoader
        arguments:
            - "@netgen_layouts.sylius.bitbag.page_repository"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: bitbag_page }

    netgen_layouts.sylius.bitbag.item.value_url_generator.page:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueUrlGenerator\PageValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: bitbag_page }

    netgen_layouts.sylius.bitbag.content_browser.template_value_provider.bitbag_page.code:
        class: Netgen\Layouts\Sylius\BitBag\Item\ColumnProvider\Page\Code
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: bitbag_page\code }

    netgen_layouts.sylius.bitbag.content_browser.template_value_provider.bitbag_page.slug:
        class: Netgen\Layouts\Sylius\BitBag\Item\ColumnProvider\Page\Slug
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: bitbag_page\slug }

    netgen_layouts.sylius.bitbag.item.value_converter.section:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueConverter\SectionValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.bitbag.item.value_loader.section:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueLoader\SectionValueLoader
        arguments:
            - "@netgen_layouts.sylius.bitbag.section_repository"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: bitbag_section }

    netgen_layouts.sylius.bitbag.item.value_url_generator.section:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueUrlGenerator\SectionValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: bitbag_section }

    netgen_layouts.sylius.bitbag.content_browser.template_value_provider.bitbag_section.code:
        class: Netgen\Layouts\Sylius\BitBag\Item\ColumnProvider\Section\Code
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: bitbag_section\code }

    netgen_layouts.sylius.bitbag.item.value_converter.block:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueConverter\BlockValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.bitbag.item.value_loader.block:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueLoader\BlockValueLoader
        arguments:
            - "@netgen_layouts.sylius.bitbag.block_repository"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: bitbag_block }

    netgen_layouts.sylius.bitbag.item.value_url_generator.block:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueUrlGenerator\BlockValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: bitbag_block }

    netgen_layouts.sylius.bitbag.content_browser.template_value_provider.bitbag_block.code:
        class: Netgen\Layouts\Sylius\BitBag\Item\ColumnProvider\Block\Code
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: bitbag_block\code }

    netgen_layouts.sylius.bitbag.item.value_converter.media:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueConverter\MediaValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.bitbag.item.value_loader.media:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueLoader\MediaValueLoader
        arguments:
            - "@netgen_layouts.sylius.bitbag.media_repository"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: bitbag_media }

    netgen_layouts.sylius.bitbag.item.value_url_generator.media:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueUrlGenerator\MediaValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: bitbag_media }

    netgen_layouts.sylius.bitbag.content_browser.template_value_provider.bitbag_media.code:
        class: Netgen\Layouts\Sylius\BitBag\Item\ColumnProvider\Media\Code
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: bitbag_media\code }

    netgen_layouts.sylius.bitbag.content_browser.template_value_provider.bitbag_media.type:
        class: Netgen\Layouts\Sylius\BitBag\Item\ColumnProvider\Media\Type
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: bitbag_media\type }

    netgen_layouts.sylius.bitbag.content_browser.template_value_provider.bitbag_media.mime_type:
        class: Netgen\Layouts\Sylius\BitBag\Item\ColumnProvider\Media\MimeType
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: bitbag_media\mime_type }

    netgen_layouts.sylius.bitbag.item.value_converter.frequently_asked_question:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueConverter\FrequentlyAskedQuestionValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.bitbag.item.value_loader.frequently_asked_question:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueLoader\FrequentlyAskedQuestionValueLoader
        arguments:
            - "@netgen_layouts.sylius.bitbag.frequently_asked_question_repository"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: bitbag_frequently_asked_question }

    netgen_layouts.sylius.bitbag.item.value_url_generator.frequently_asked_question:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueUrlGenerator\FrequentlyAskedQuestionValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: bitbag_frequently_asked_question }

