services:
    netgen_layouts.sylius.bitbag.item.value_converter.page:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueConverter\PageValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.bitbag.item.value_loader.page:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueLoader\PageValueLoader
        arguments:
            - "@netgen_layouts.sylius.bitbag.page_repository"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: bitbag_page }

    netgen_layouts.sylius.bitbag.item.value_url_generator.page:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueUrlGenerator\PageValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: bitbag_page }

    netgen_layouts.sylius.bitbag.item.value_converter.section:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueConverter\SectionValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.bitbag.item.value_loader.section:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueLoader\SectionValueLoader
        arguments:
            - "@netgen_layouts.sylius.bitbag.section_repository"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: bitbag_section }

    netgen_layouts.sylius.bitbag.item.value_url_generator.section:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueUrlGenerator\SectionValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: bitbag_section }

    netgen_layouts.sylius.bitbag.item.value_converter.block:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueConverter\BlockValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.bitbag.item.value_loader.block:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueLoader\BlockValueLoader
        arguments:
            - "@netgen_layouts.sylius.bitbag.block_repository"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: bitbag_block }

    netgen_layouts.sylius.bitbag.item.value_url_generator.block:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueUrlGenerator\BlockValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: bitbag_block }

    netgen_layouts.sylius.bitbag.item.value_converter.media:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueConverter\MediaValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.bitbag.item.value_loader.media:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueLoader\MediaValueLoader
        arguments:
            - "@netgen_layouts.sylius.bitbag.media_repository"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: bitbag_media }

    netgen_layouts.sylius.bitbag.item.value_url_generator.media:
        class: Netgen\Layouts\Sylius\BitBag\Item\ValueUrlGenerator\MediaValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: bitbag_media }
