services:
    netgen_layouts.sylius.bitbag.parameters.parameter_type.section:
        class: Netgen\Layouts\Sylius\BitBag\Parameters\ParameterType\SectionType
        tags:
            - { name: netgen_layouts.parameter_type }

    netgen_layouts.sylius.bitbag.parameters.form_mapper.section:
        class: Netgen\Layouts\Sylius\BitBag\Parameters\Form\Mapper\SectionMapper
        tags:
            - { name: netgen_layouts.parameter_type.form_mapper, type: bitbag_section }
