services:
    netgen_layouts.sylius.bitbag.page_repository:
        class: Netgen\Layouts\Sylius\BitBag\Repository\PageRepository
        parent: bitbag_sylius_cms_plugin.repository.page

    netgen_layouts.sylius.bitbag.section_repository:
        class: Netgen\Layouts\Sylius\BitBag\Repository\SectionRepository
        parent: bitbag_sylius_cms_plugin.repository.section

    netgen_layouts.sylius.bitbag.block_repository:
        class: Netgen\Layouts\Sylius\BitBag\Repository\BlockRepository
        parent: bitbag_sylius_cms_plugin.repository.block
