services:
    netgen_layouts.sylius.bitbag.templating.twig.extension.bitbag:
        class: Netgen\Bundle\LayoutsSyliusBitBagBundle\Templating\Twig\Extension\BitBagExtension
        tags:
            - { name: twig.extension }

    netgen_layouts.sylius.bitbag.templating.twig.runtime.bitbag:
        class: Netgen\Bundle\LayoutsSyliusBitBagBundle\Templating\Twig\Runtime\BitBagRuntime
        arguments:
            - "@netgen_layouts.sylius.bitbag.page_repository"
            - "@netgen_layouts.sylius.bitbag.section_repository"
        tags:
            - { name: twig.runtime }
