services:
    netgen_layouts.sylius.view.matcher.sylius_resource.view_type:
        class: Netgen\Layouts\Sylius\BitBag\View\Matcher\SyliusResource\BitBagComponentIdentifier
        tags:
            - { name: netgen_layouts.view_matcher, identifier: bitbag_component\identifier }
