view:
    item_view:
        default:
            bitbag_page:
                template: "@nglayouts/item/bitbag_page.html.twig"
                match:
                    item\value_type: bitbag_page
        ajax:
            bitbag_page:
                template: "@nglayouts/item/bitbag_page.html.twig"
                match:
                    item\value_type: bitbag_page
        app:
            bitbag_page:
                template: "@NetgenLayoutsSyliusBitBag/app/item/view/bitbag_page.html.twig"
                match:
                    item\value_type: bitbag_page
