view:
    item_view:
        default:
            bitbag_page:
                template: "@nglayouts/item/bitbag_page.html.twig"
                match:
                    item\value_type: bitbag_page
            bitbag_section:
                template: "@nglayouts/item/bitbag_section.html.twig"
                match:
                    item\value_type: bitbag_section
            bitbag_block:
                template: "@nglayouts/item/bitbag_block.html.twig"
                match:
                    item\value_type: bitbag_block
            bitbag_media:
                template: "@nglayouts/item/bitbag_media.html.twig"
                match:
                    item\value_type: bitbag_media
            bitbag_frequently_asked_question:
                template: "@nglayouts/item/bitbag_frequently_asked_question.html.twig"
                match:
                    item\value_type: bitbag_frequently_asked_question
        ajax:
            bitbag_page:
                template: "@nglayouts/item/bitbag_page.html.twig"
                match:
                    item\value_type: bitbag_page
            bitbag_section:
                template: "@nglayouts/item/bitbag_section.html.twig"
                match:
                    item\value_type: bitbag_section
            bitbag_block:
                template: "@nglayouts/item/bitbag_block.html.twig"
                match:
                    item\value_type: bitbag_block
            bitbag_media:
                template: "@nglayouts/item/bitbag_media.html.twig"
                match:
                    item\value_type: bitbag_media
            bitbag_frequently_asked_question:
                template: "@nglayouts/item/bitbag_frequently_asked_question.html.twig"
                match:
                    item\value_type: bitbag_frequently_asked_question
        app:
            bitbag_page:
                template: "@NetgenLayoutsSyliusBitBag/app/item/view/bitbag_page.html.twig"
                match:
                    item\value_type: bitbag_page
            bitbag_section:
                template: "@NetgenLayoutsSyliusBitBag/app/item/view/bitbag_section.html.twig"
                match:
                    item\value_type: bitbag_section
            bitbag_block:
                template: "@NetgenLayoutsSyliusBitBag/app/item/view/bitbag_block.html.twig"
                match:
                    item\value_type: bitbag_block
            bitbag_media:
                template: "@NetgenLayoutsSyliusBitBag/app/item/view/bitbag_media.html.twig"
                match:
                    item\value_type: bitbag_media
            bitbag_frequently_asked_question:
                template: "@NetgenLayoutsSyliusBitBag/app/item/view/bitbag_frequently_asked_question.html.twig"
                match:
                    item\value_type: bitbag_frequently_asked_question
