view:
    rule_target_view:
        value:
            bitbag_page:
                template: "@NetgenLayoutsSyliusBitBag/admin/layout_resolver/target/value/page.html.twig"
                match:
                    rule_target\type: bitbag_page
