orm:
    entity_managers:
        default:
            mappings:
                NetgenLayoutsSyliusBitBagBundle:
                    type: xml
                    prefix: Netgen\Layouts\Sylius\BitBag\Component
                    dir: "%kernel.project_dir%/vendor/netgen/layouts-sylius-bitbag/bundle/Resources/config/doctrine"
                    is_bundle: false
