item_types:
    bitbag_page:
        name: item_types.bitbag_page
        tree:
            enabled: false
        preview:
            enabled: false
        columns:
            name:
                name: columns.name
                value_provider: name
        default_columns:
            - name
    bitbag_section:
        name: item_types.bitbag_section
        tree:
            enabled: false
        preview:
            enabled: false
        columns:
            name:
                name: columns.name
                value_provider: name
        default_columns:
            - name
    bitbag_block:
        name: item_types.bitbag_block
        tree:
            enabled: false
        preview:
            enabled: false
        columns:
            name:
                name: columns.name
                value_provider: name
        default_columns:
            - name
    bitbag_media:
        name: item_types.bitbag_media
        tree:
            enabled: false
        preview:
            template: '@NetgenLayoutsSyliusBitBag/app/ngcb/bitbag_media.html.twig'
        columns:
            name:
                name: columns.name
                value_provider: name
        default_columns:
            - name
