item_types:
    bitbag_page:
        name: item_types.bitbag_page
        tree:
            enabled: false
        preview:
            enabled: false
        columns:
            name:
                name: columns.name
                value_provider: name
        default_columns:
            - name
    bitbag_section:
        name: item_types.bitbag_section
        tree:
            enabled: false
        preview:
            enabled: false
        columns:
            name:
                name: columns.name
                value_provider: name
        default_columns:
            - name
