filter_sets:
    nglayouts_sylius_bitbag_page_app_preview:
        filters:
            thumbnail: { size: [160, 90], mode: outbound }
            strip: ~
    nglayouts_sylius_bitbag_media_app_preview:
        filters:
            thumbnail: { size: [ 160, 90 ], mode: outbound }
            strip: ~
