resource_type_condition:
    available_resources:
      BitBag\SyliusCmsPlugin\Entity\PageInterface: page
      BitBag\SyliusCmsPlugin\Entity\SectionInterface: section

page_target:
    available_pages:
        bitbag_sylius_cms_plugin_shop_frequently_asked_question_index: frequently_asked_questions
