query_types:
    bitbag_page:
        name: 'BitBag page'
    bitbag_block:
        name: 'BitBag block'
    bitbag_media:
        name: 'BitBag media'
    bitbag_section:
        name: 'BitBag section'
