value_types:
    bitbag_page:
        name: 'BitBag page'
    bitbag_section:
        name: 'BitBag section'
    bitbag_block:
        name: 'BitBag block'
    bitbag_media:
        name: 'BitBag media'
    bitbag_frequently_asked_question:
        name: 'BitBag frequently asked question'
